version: "3"
services:
  docker-t:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3332:3333"
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "serve"]
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "lint"]
