name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/build-push-action@v4.1.1
      with:
        file: ./Dockerfile.dev
        tags: snowtreetree/docker-t
    - name: npm run lint
      run: docker run -e CI=true snowtreetree/docker-t npm run lint
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v4.1.8
        with:
          # Private key part of an SSH key pair
          SSH_PRIVATE_KEY: 
          # Remote host
          REMOTE_HOST: 
          # Remote user
          REMOTE_USER: 
          # Remote port
          REMOTE_PORT: # optional, default is 22
          # Source directory, path relative to `$GITHUB_WORKSPACE` root, eg: `dist/`
          SOURCE: # optional, default is 
          # Target directory
          TARGET: # optional, default is 
          # Arguments to pass to rsync
          ARGS: # optional, default is -rlgoDzvc -i
          # An array of ssh arguments, they must be prefixed with -o and separated by a comma, for example: -o SomeArgument=no, -o SomeOtherArgument=5 
          SSH_CMD_ARGS: # optional, default is -o StrictHostKeyChecking=no
          # paths to exclude separated by `,`, ie: `/dist/, /node_modules/`
          EXCLUDE: # optional, default is 
          # Script to run on host machine before rsync
          SCRIPT_BEFORE: # optional, default is 
          # Script to run on host machine after rsync
          SCRIPT_AFTER: # optional, default is 
          
          
          
          
          
          
          
          
          
          
          
