name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/build-push-action@v4.1.1
      with:
        file: ./Dockerfile.dev
    - name: Build the Docker image
      run: docker build --tag snowtreetree/docker-t .
    - name: npm run lint
      run: docker run -e CI=true snowtreetree/docker-t npm run lint
