name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/build-push-action@v4.1.1
      with:
        file: ./Dockerfile.dev
        tags: snowtreetree/docker-t
    - name: npm run build
      run: docker run -e CI=true snowtreetree/docker-t npm run lint
    - name: Prepare SSH
      run: >
        cd ~ && mkdir .ssh &&
        touch ~/.ssh/known_hosts &&
        ssh-keyscan -H "$IP" >>~/.ssh/known_hosts
      env:
        IP: ${{ secrets.REMOTE_HOST }}
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v4.1.8
      with:
        # Private key part of an SSH key pair
        SSH_PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
        # Remote host
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        # Remote user
        REMOTE_USER: root
        SOURCE: dist/
        TARGET: docker-t

          
          
          
          
          
          
          
          
          
          
