name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
#     - uses: docker/build-push-action@v4.1.1
#       with:
#         file: ./Dockerfile.dev
#         tags: snowtreetree/docker-t
#     - name: npm run build
#       run: docker run snowtreetree/docker-t npm run lint
    - name: Checkout
      uses: actions/checkout@v3.5.3
    - name: pwd
      run: pwd 
    - name: cd 
      run: ls -a
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v4.1.8
      with:
        # Private key part of an SSH key pair
        SSH_PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
        # Remote host
        REMOTE_HOST: 106.14.156.134
        # Remote user
        REMOTE_USER: root
        TARGET: docker-t

          
          
          
          
          
          
          
          
          
          
